enum
{
	PIVOT_MASTER_PLUGIN_NAME    =   1000,
	PIVOT_MASTER_ABOUT          =   1001,
	PIVOT_MASTER_ALERT_OBJ      =   1002,
	PIVOT_MASTER_ALERT_NULL     =   1003,
	PIVOT_MASTER_GROUP_PROGRESS =   1004,
	PIVOT_MASTER_TEXT_PROGRESS  =   1005,
	PIVOT_MASTER_PROGRESS       =   1006,

    _DUMMY_ELEMENT_
};
