enum
{
    PIVOT_MASTER_PLUGIN_NAME	= 	1000,
	PIVOT_MASTER_ABOUT          =   1001,
	PIVOT_MASTER_ALERT_OBJ      =   1002,
	PIVOT_MASTER_ALERT_NULL     =   1003,
	PIVOT_MASTER_ALERT_MULTI    =   1004,

    _DUMMY_ELEMENT_
};
